services:
  mysql:
    image: mysql:latest 
    container_name: tradingjournal
    restart: always
    environment:
      MYSQL_DATABASE: trading_journal
      MYSQL_USER: journal_user
      MYSQL_PASSWORD: journal_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  db_data:
