services:
  mysql:
    image: mysql:latest 
    container_name: tradingjournal
    restart: always
    environment:
      MYSQL_DATABASE: '{MYSQL_DATABASE}'
      MYSQL_USER: '{MYSQL_USER}'
      MYSQL_PASSWORD: '{MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '{MYSQL_ROOT_PASSWORD}'
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  db_data:
